spring:
  rabbitmq:
    host: 192.168.202.129
    username: wjl
    password: wjl
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"