server:
  port: 8011
spring:
  profiles:
    active: query_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://httpbin.org:80/get
        predicates:
        - After=2019-05-20T17:42:47.789-07:00[America/Denver]
  profiles: after_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: http://httpbin.org:80/get
        predicates:
        - Header=X-Request-Id, \d+
  profiles: header_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: http://httpbin.org:80/get
        predicates:
        - Cookie=name, wjl
  profiles: cookie_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: https://www.baidu.com
        predicates:
        - Host=**.wjl.com
  profiles: host_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: https://www.baidu.com
        predicates:
        - Method=GET
  profiles: method_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: https://www.baidu.com
        predicates:
        - Path=/wjl/{segment}
  profiles: path_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: http://httpbin.org:80/get
        predicates:
        - Query=name, wjl
  profiles: query_route