spring:
  profiles: mongodb1
  data:
    mongodb:
      database: testDB
      host: 192.168.1.46
      port: 27017
      username: wjl
      password: wjl
---        
spring:
  profiles: mongodb1
  data:
    mongodb:
      database: testDB1
      host: 192.168.1.46
      port: 27017
      username: wjl
      password: wjl
