spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SkillKingwjl/spring-cloud-learning/
          search-paths: config-files
          username: 383188327@qq.com
          password: wei6446320
      label: master
server:
  port: 8888
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
